-- CREATE DATABASE LinhKienDienTuQly;
-- GO

USE LinhKienDienTuQly;
GO


CREATE TABLE Nha_Cung_Cap (
    MaNCC CHAR(10) NOT NULL, --PK
    TenNCC NVARCHAR(50),
    SDT VARCHAR(15),
    DiaChi NVARCHAR(100)
    CONSTRAINT PK_MaNCC PRIMARY KEY (MaNCC)
);
GO

CREATE TABLE Nhan_Vien (
    MaNV CHAR(10) NOT NULL, --PK
    TenNV NVARCHAR(50),
    SDT VARCHAR(15),
    ChucVu NVARCHAR(30),
    CONSTRAINT PK_MaNV PRIMARY KEY (MaNV)
);
GO

CREATE TABLE Khach_Hang (
    MaKH CHAR(10) NOT NULL, --PK
    TenKH NVARCHAR(50),
    SDT VARCHAR(15),
    DiaChi NVARCHAR(100),

    CONSTRAINT PK_MaKH PRIMARY KEY (MaKH)
);
GO

CREATE TABLE San_Pham (
    MaSP CHAR(10) NOT NULL, --PK
    TenSP NVARCHAR(100) NOT NULL,
    LoaiSanPham NVARCHAR(50), -- Không ràng buộc CHECK,
    Gia DECIMAL(18,2) DEFAULT 0,
    SoLuongTonKho INT DEFAULT 0,

    CONSTRAINT PK_MaSP PRIMARY KEY (MaSP)
);
GO

CREATE TABLE Hoa_Don_Ban_Hang (
    MaHD CHAR(10) NOT NULL, --PK 
    NgayBan DATE DEFAULT GETDATE(),
    MaNV CHAR(10) NOT NULL, --FK
    MaKH CHAR(10) NOT NULL, --FK

    CONSTRAINT PK_HDBH PRIMARY KEY (MaHD),
    CONSTRAINT FK_HDBH_MaNV FOREIGN KEY (MaNV) REFERENCES Nhan_Vien(MaNV) ON DELETE CASCADE,
    CONSTRAINT FK_HDBH_MaKH FOREIGN KEY (MaKH) REFERENCES Khach_Hang(MaKH) ON DELETE CASCADE
);
GO

CREATE TABLE Hoa_Don_Nhap_Hang (
    MaPN CHAR(10) NOT NULL, --PK
    NgayNhap DATE DEFAULT GETDATE(),
    MaNV CHAR(10) NOT NULL, --FK
    MaNCC CHAR(10) NOT NULL, --FK
    CONSTRAINT PK_HDNH PRIMARY KEY (MaPN),
    CONSTRAINT FK_HDNH_MaNV FOREIGN KEY (MaNV) REFERENCES Nhan_Vien(MaNV) ON DELETE CASCADE, 
    CONSTRAINT FK_HDNH_MaNCC FOREIGN KEY (MaNCC) REFERENCES Nha_Cung_Cap(MaNCC) ON DELETE CASCADE
);
GO

CREATE TABLE ChiTiet_HD_Nhap (
    MaPN CHAR(10) NOT NULL, --PK,FK
    MaSP CHAR(10) NOT NULL, --PK,FK
    SoLuong INT DEFAULT 0,
    GiaNhap DECIMAL(18,2) DEFAULT 0,
    CONSTRAINT PK_CTHDN PRIMARY KEY (MaPN, MaSP),
    CONSTRAINT FK_CTHDN_MaPN FOREIGN KEY (MaPN) REFERENCES Hoa_Don_Nhap_Hang(MaPN) ON DELETE CASCADE, 
    CONSTRAINT FK_CTHDN_MaSP FOREIGN KEY (MaSP) REFERENCES San_Pham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE ChiTiet_HD_Ban (
    MaHD CHAR(10) NOT NULL, --PK,FK
    MaSP CHAR(10) NOT NULL, --PK,FK
    SoLuong INT DEFAULT 0,
    Gia DECIMAL(18,2) DEFAULT 0, 

    CONSTRAINT PK_CTHDB PRIMARY KEY (MaHD, MaSP),
    CONSTRAINT FK_CTHDB_MaHD FOREIGN KEY (MaHD) REFERENCES Hoa_Don_Ban_Hang(MaHD) ON DELETE CASCADE, 
    CONSTRAINT FK_CTHDB_MaSP FOREIGN KEY (MaSP) REFERENCES San_Pham(MaSP) ON DELETE CASCADE
);
GO

CREATE TABLE Cung_Cap (
    MaNCC CHAR(10) NOT NULL, --PK,FK
    MaSP CHAR(10) NOT NULL, --PK,FK

    CONSTRAINT PK_CC PRIMARY KEY (MaNCC, MaSP),
    CONSTRAINT FK_CC_MaNCC FOREIGN KEY (MaNCC) REFERENCES Nha_Cung_Cap(MaNCC) ON DELETE CASCADE, 
    CONSTRAINT FK_CC_MaSP FOREIGN KEY (MaSP) REFERENCES San_Pham(MaSP) ON DELETE CASCADE
);
GO