USE LinhKienDienTuQly

CREATE TABLE Nha_Cung_Cap(
    MaNCC CHAR(10) NOT NULL, --PK
    TenNCC NVARCHAR(20),
    SDT CHAR(10),
    DiaChi NVARCHAR(25),

    CONSTRAINT PK_MaNCC PRIMARY KEY (MaNCC)
);
GO

CREATE TABLE Nhan_Vien(
    MaNV CHAR(10) NOT NULL, --PK
    Ten NVARCHAR(20),
    SDT CHAR(10),
    ChucVu NVARCHAR(10),

    CONSTRAINT PK_MaNV PRIMARY KEY (MaNV)
);
GO

CREATE TABLE Khach_Hang(
    MaKH CHAR(10) NOT NULL, --PK
    Ten NVARCHAR(20),
    SDT CHAR(10),
    DiaChi NVARCHAR(25),
    
    CONSTRAINT PK_MaKH PRIMARY KEY (MaKH)
);
GO

CREATE TABLE San_Pham(
    MaSP CHAR(10) NOT NULL, --PK
    Ten NVARCHAR(100) NOT NULL,
    LoaiSanPham NVARCHAR(50) NOT NULL 
    CHECK (LoaiSanPham IN ('Monitor', 'RAM', 'CPU', 'GPU', 'Fan', 'Mouse','Others')),
    Gia DECIMAL(18,2),
    SoLuongTonKho INT DEFAULT 0

    CONSTRAINT PK_MaSP PRIMARY KEY (MaSP)

);
GO


CREATE TABLE Hoa_Don_Ban_Hang(
    MaHD CHAR(10) NOT NULL, --PK
    NgayNhap DATE,
    MaNV CHAR(10) NOT NULL, --FK
    MaKH CHAR(10) NOT NULL, --FK

    CONSTRAINT PK_MaHD PRIMARY KEY (MaHD),
    CONSTRAINT FK_HDBH_MaNV FOREIGN KEY(MaNV) REFERENCES Nhan_Vien(MaNV),
    CONSTRAINT FK_HDBH_MaKH FOREIGN KEY(MaKH) REFERENCES Khach_Hang(MaKH)
);
GO

CREATE TABLE Hoa_Don_Nhap_Hang(
    MaPN CHAR(10) NOT NULL, --PK
    NgayNhap DATE,
    MaNV CHAR(10) NOT NULL, -- FK
    MaNCC CHAR(10) NOT NULL, --FK

    CONSTRAINT PK_MaPN PRIMARY KEY (MaPN),
    CONSTRAINT FK_HDNH_MaNV FOREIGN KEY(MaNV) REFERENCES Nhan_Vien(MaNV),
    CONSTRAINT FK_HDNH_MaNCC FOREIGN KEY(MaNCC) REFERENCES Nha_Cung_Cap(MaNCC),
);
GO


CREATE TABLE ChiTiet_HD_Nhap(
    MaPN CHAR(10) NOT NULL, --FK
    MaSP CHAR(10) NOT NULL, --FK
    SoLuong INT DEFAULT 0,
    Gia DECIMAL(18,2)

    CONSTRAINT FK_CTHDN_MaSP FOREIGN KEY(MaSP) REFERENCES San_Pham(MaSP),
    CONSTRAINT FK_CTHDN_MaPN FOREIGN KEY(MaPN) REFERENCES Hoa_Don_Nhap_Hang(MaPN),
);

CREATE TABLE ChiTiet_HD_Ban(
    MaHD CHAR(10) NOT NULL, --FK
    MaSP CHAR(10) NOT NULL, --FK
    SoLuong INT DEFAULT 0,
    Gia DECIMAL(18,2)

    CONSTRAINT FK_CTHDN_MaSP FOREIGN KEY(MaSP) REFERENCES San_Pham(MaSP),
    CONSTRAINT FK_CTHDN_MaHD FOREIGN KEY(MaHD) REFERENCES Hoa_Don_Ban_Hang(MaHD),
);

CREATE TABLE Cung_Cap(
    MaNCC CHAR(10) NOT NULL, --FK
    MaSP CHAR(10) NOT NULL, --FK

    CONSTRAINT FK_CTHDN_MaSP FOREIGN KEY(MaSP) REFERENCES San_Pham(MaSP),
    CONSTRAINT FK_CC_MaNCC FOREIGN KEY(MaNCC) REFERENCES Nha_Cung_Cap(MaNCC)
);
